api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: [
            '%kernel.project_dir%/src/Entity',
            '%kernel.project_dir%/src/ApiResource',
        ]
    patch_formats:
        json: ['application/merge-patch+json']
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
